spring.application.name=powercut-predictor
server.port=8080

spring.datasource.url=jdbc:h2:mem:powercut;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jackson.serialization.write-dates-as-timestamps=false
management.endpoints.web.exposure.include=health,info
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
weather.api.key=2fc6bf0de5f941859f7a5874d820bc95
weather.api.url=https://api.openweathermap.org/data/2.5/weather
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=parameswarip369@gmail.com
spring.mail.password=SpiderMan#06
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
jwt.secret=powercut-predictor-secret-key-2024-chennai
jwt.expiration=86400000